import fs from 'fs';
import path from 'path';
import { parseFile } from 'music-metadata';

// Make sure public/music and public/covers exist
const UPLOAD_DIR = path.join(process.cwd(), 'music');
const MUSIC_DIR = path.join(process.cwd(), 'public', 'music');
const COVERS_DIR = path.join(process.cwd(), 'public', 'covers');
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'app', 'data.js');

if (!fs.existsSync(MUSIC_DIR)) fs.mkdirSync(MUSIC_DIR, { recursive: true });
if (!fs.existsSync(COVERS_DIR)) fs.mkdirSync(COVERS_DIR, { recursive: true });

async function syncMusic() {
  if (fs.existsSync(UPLOAD_DIR)) {
    console.log('Found /music folder. Copying items to /public/music...');
    const uploadFiles = fs.readdirSync(UPLOAD_DIR);
    for (const f of uploadFiles) {
      if (f.match(/\.(mp3|m4a|wav|flac)$/i)) {
        fs.copyFileSync(path.join(UPLOAD_DIR, f), path.join(MUSIC_DIR, f));
      }
    }
  }

  console.log('Scanning for music files in public/music...');
  const files = fs.readdirSync(MUSIC_DIR)
    .filter(file => file.endsWith('.mp3') || file.endsWith('.m4a') || file.endsWith('.wav') || file.endsWith('.flac'));

  if (files.length === 0) {
    console.log('No music files found in /music or /public/music. Please add some and run this script again. Your current fake music will remain in place for now.');
    return;
  }

  const songs = [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(MUSIC_DIR, file);
    try {
      const metadata = await parseFile(filePath);
      const tags = metadata.common;
      
      let albumArt = "https://images.unsplash.com/photo-1616820026280-127912e3591a?w=400&q=80"; // fallback

      // Extract cover art
      if (tags.picture && tags.picture.length > 0) {
        const cover = tags.picture[0];
        const ext = cover.format === 'image/png' ? 'png' : 'jpg';
        const coverName = `cover_${i + 1}.${ext}`;
        const coverPath = path.join(COVERS_DIR, coverName);
        fs.writeFileSync(coverPath, cover.data);
        albumArt = `/covers/${coverName}`;
      }

      songs.push({
        id: i + 1,
        title: tags.title || file.replace(/\.[^/.]+$/, ""),
        artist: tags.artist || "Unknown Artist",
        duration: Math.round(metadata.format.duration || 0),
        albumArt: albumArt,
        genre: (tags.genre && tags.genre.length > 0) ? tags.genre[0] : "Music",
        url: `/music/${file}`
      });
      
      console.log(`Processed: ${songs[songs.length - 1].title}`);
    } catch (err) {
      console.error(`Error processing ${file}:`, err);
    }
  }

  // Preserve existing playlists and formatTime function
  const dataContent = `// Auto-generated by sync-music.js
export const SONGS = ${JSON.stringify(songs, null, 2)};

export const PLAYLISTS = [
{ id: 1, name: "Liked Songs", songIds: [1, 3] },
{ id: 2, name: "Focus & Flow", songIds: [2] }
];

export function formatTime(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return \`\${m}:\${s < 10 ? '0' : ''}\${s}\`;
}
`;

  fs.writeFileSync(OUTPUT_FILE, dataContent);
  console.log('\\nSuccessfully synchronized music!');
  console.log('You can now see your real music in the app.');
}

syncMusic();
